# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: XenServer.XenServerVMTools
PackageVersion: 9.3.2
InstallerLocale: en-US
InstallerType: wix
Installers:
- InstallerUrl: http://downloadns.citrix.com.edgesuite.net/17480/managementagentx64.msi
  Architecture: x64
  InstallerSha256: 74473FB1A1CA9BCFEE933310B1A83A971698B0405AAF6EF45BB32393925F6286
  ProductCode: '{76E2E9A8-9927-4AFE-8F0C-D0036FFF5FA5}'
- InstallerUrl: http://downloadns.citrix.com.edgesuite.net/17481/managementagentx86.msi
  Architecture: x86
  InstallerSha256: B0FA92E6B361B63EDC91AA59DA5FAF22EA16584975CC2CCBA4A8FB322431FA2C
  ProductCode: '{54928895-6B86-40AC-AFA1-6F75561E7E14}'
ManifestType: installer
ManifestVersion: 1.6.0
